# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ORKa.MV Data API
                                 A QGIS plugin
 This plugin downloads a geopackage from the ORKa.MV Data API
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-05-03
        copyright            : (C) 2021 by terrestris GmbH & Co. KG
        email                : info@terrestris.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OrkamvDataApiPlugin class from file orkamv_data_api_plugin.py

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .orkamv_data_api_plugin import OrkamvDataApiPlugin
    return OrkamvDataApiPlugin(iface)
