# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OrkamvVisibilityTogglePluginDialog
                                 A QGIS plugin
 This plugin downloads a geopackage from the ORKa.MV Data API
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-01-18
        git sha              : $Format:%H$
        copyright            : (C) 2021 by terrestris GmbH & Co. KG
        email                : info@terrestris.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from PyQt5.QtWidgets import QPushButton, QLineEdit, QProgressBar, QComboBox, QRadioButton, QVBoxLayout, \
    QScrollArea, QWidget
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
from qgis._gui import QgsExtentWidget, QgsFileWidget

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'orkamv_visibility_toggle_plugin_dialog_base.ui'))


class OrkamvVisibilityTogglePluginDialog(QtWidgets.QDialog, FORM_CLASS):

    layer_select_groups_area: QScrollArea
    layer_select_groups: QWidget
    layer_select_combo: QComboBox

    def __init__(self, parent=None):
        """Constructor."""
        super(OrkamvVisibilityTogglePluginDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        #
        # self.extent_widget = QgsExtentWidget(parent=self, style=QgsExtentWidget.ExpandedStyle)
        # self.extent_placeholder.addWidget(self.extent_widget)

